import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { MatchProvider } from "@/context/MatchContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Companion Matcher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <MatchProvider>
          <Toaster />
          {children}
          <div className='w-full bg-gray-800 text-white text-center p-3'>
            <h1>Made By vanshrajput099@gmail.com</h1>
          </div>
        </MatchProvider>
      </body>
    </html>
  );
}
